# Generated by Django 5.2.15 on 2026-06-19 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trips", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("hotel", "Hotel / Accommodation"),
                            ("food", "Food & Dining"),
                            ("toll", "Toll"),
                            ("fuel", "Fuel"),
                            ("shopping", "Shopping"),
                            ("entertainment", "Entertainment"),
                            ("adventure", "Adventure Activity"),
                            ("sightseeing", "Sightseeing / Entry Tickets"),
                            ("flight", "Flight"),
                            ("train", "Train"),
                            ("bus", "Bus"),
                            ("cab", "Cab / Taxi"),
                            ("boat", "Boat / Ferry"),
                            ("metro", "Metro / Local Transport"),
                            ("parking", "Parking"),
                            ("miscellaneous", "Miscellaneous"),
                        ],
                        max_length=30,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField()),
                ("description", models.CharField(blank=True, max_length=255)),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "split_type",
                    models.CharField(
                        choices=[
                            ("single", "Not split (single payer)"),
                            ("equal", "Split equally"),
                            ("custom", "Custom split"),
                        ],
                        default="single",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses_logged",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paid_expenses",
                        to="trips.tripparticipant",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseSplit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="splits",
                        to="expenses.expense",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_shares",
                        to="trips.tripparticipant",
                    ),
                ),
            ],
            options={
                "unique_together": {("expense", "participant")},
            },
        ),
    ]
