# Generated by Django 5.2.15 on 2026-06-19 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
        ("trips", "0002_hotel_itineraryday_categorybudget"),
    ]

    operations = [
        migrations.AddField(
            model_name="placereview",
            name="hotel",
            field=models.ForeignKey(
                blank=True,
                help_text="Link this review to a hotel booking, if applicable.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews",
                to="trips.hotel",
            ),
        ),
    ]
