# Generated by Django 5.2.15 on 2026-06-19 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("check_in_date", models.DateField(blank=True, null=True)),
                ("check_out_date", models.DateField(blank=True, null=True)),
                (
                    "meal_plan",
                    models.CharField(
                        choices=[
                            ("none", "No meals included"),
                            ("breakfast", "Breakfast included"),
                            ("breakfast_dinner", "Breakfast & Dinner included"),
                            ("all_meals", "All meals included"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "booking_status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned (not booked)"),
                            ("booked", "Booked"),
                            ("completed", "Stay completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotels",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["check_in_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="ItineraryDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("event", models.CharField(blank=True, max_length=255)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Free-form day plan / things to do"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "hotel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="itinerary_days",
                        to="trips.hotel",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itinerary_days",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="CategoryBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=30)),
                (
                    "allocated_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_budgets",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["category"],
                "unique_together": {("trip", "category")},
            },
        ),
    ]
